basePath: /
definitions: {}
info:
    description: 'kyc-moongoose server'
    title: 'API - Documentation'
    version: 1.0.0
paths: {}
swagger: '2.0'
securityDefinitions: {}
consumes:
    - application/json
produces:
    - application/json
